/**
 * The signal registry — 40 weighted inputs across the 5 published categories.
 *
 * 17 core signals come from SCORING_SIGNALS_AND_ACCURACY (published weights).
 * 23 "edge" signals are leading indicators: publicly obtainable, painful to track
 * by hand, and they move before price does. They carry a lead-time band and a
 * why-nobody-tracks-this line, and they feed the SAME single investment score.
 *
 * Category weights are fixed. Within a category, raw weights are renormalised so
 * the category sums to its published weight — so adding signal 41 never changes
 * what a category is worth.
 */

export const CATEGORIES = [
  { key: "growth", label: "Growth Indicators", weight: 35 },
  { key: "housing", label: "Housing Market Dynamics", weight: 25 },
  { key: "infrastructure", label: "Infrastructure Development", weight: 20 },
  { key: "quality", label: "Quality of Life", weight: 15 },
  { key: "economic", label: "Economic Fundamentals", weight: 5 },
] as const;

export type CategoryKey = (typeof CATEGORIES)[number]["key"];

/** A scoring band: value in [lo, hi) maps linearly onto [s0, s1]. */
export type Band = [lo: number, hi: number, s0: number, s1: number];

export type SignalDef = {
  key: string;
  label: string;
  category: CategoryKey;
  /** Raw weight — renormalised within the category by weightedDefs(). */
  raw: number;
  unit: string;
  leadMonthsLow: number;
  leadMonthsHigh: number;
  higherIsBetter: boolean;
  providerKey: string;
  core: boolean;
  whyIgnored: string;
  curve: Band[];
  /** Plausible seed values [at the weakest ZIP, at the strongest ZIP]. */
  seed: [number, number];
};

const OPEN = 1e9;

export const SIGNALS: SignalDef[] = [
  // ── Growth Indicators (35) ───────────────────────────────────────────────────
  {
    key: "population_growth",
    label: "Population growth",
    category: "growth",
    raw: 10,
    unit: "%/yr",
    leadMonthsLow: 12,
    leadMonthsHigh: 24,
    higherIsBetter: true,
    providerKey: "census",
    core: true,
    whyIgnored: "",
    curve: [
      [-OPEN, 0, 0, 25],
      [0, 1, 25, 50],
      [1, 2, 50, 70],
      [2, 3, 70, 85],
      [3, OPEN, 85, 100],
    ],
    seed: [-0.4, 4.1],
  },
  {
    key: "job_growth",
    label: "Job growth",
    category: "growth",
    raw: 10,
    unit: "%/yr",
    leadMonthsLow: 9,
    leadMonthsHigh: 18,
    higherIsBetter: true,
    providerKey: "fred",
    core: true,
    whyIgnored: "",
    curve: [
      [-OPEN, 0, 0, 25],
      [0, 1.5, 25, 50],
      [1.5, 3, 50, 72],
      [3, 4.5, 72, 88],
      [4.5, OPEN, 88, 100],
    ],
    seed: [-0.2, 5.2],
  },
  {
    key: "income_growth",
    label: "Median income growth",
    category: "growth",
    raw: 10,
    unit: "%/yr",
    leadMonthsLow: 12,
    leadMonthsHigh: 24,
    higherIsBetter: true,
    providerKey: "census",
    core: true,
    whyIgnored: "",
    curve: [
      [-OPEN, 0, 0, 25],
      [0, 2, 25, 50],
      [2, 4, 50, 72],
      [4, 6, 72, 88],
      [6, OPEN, 88, 100],
    ],
    seed: [0.6, 6.8],
  },
  {
    key: "education_attainment",
    label: "Education attainment",
    category: "growth",
    raw: 5,
    unit: "% BA+",
    leadMonthsLow: 24,
    leadMonthsHigh: 60,
    higherIsBetter: true,
    providerKey: "census",
    core: true,
    whyIgnored: "",
    curve: [
      [-OPEN, 15, 0, 30],
      [15, 25, 30, 50],
      [25, 35, 50, 70],
      [35, 50, 70, 88],
      [50, OPEN, 88, 100],
    ],
    seed: [14, 54],
  },
  {
    key: "migration_flows",
    label: "Net in-migration (USPS + IRS)",
    category: "growth",
    raw: 8,
    unit: "% of hhlds",
    leadMonthsLow: 6,
    leadMonthsHigh: 12,
    higherIsBetter: true,
    providerKey: "census",
    core: false,
    whyIgnored: "Free federal data published in an awful format nobody wants to parse.",
    curve: [
      [-OPEN, -0.5, 0, 25],
      [-0.5, 0.5, 25, 50],
      [0.5, 1.5, 50, 72],
      [1.5, 3, 72, 90],
      [3, OPEN, 90, 100],
    ],
    seed: [-0.8, 3.6],
  },
  {
    key: "employer_announcements",
    label: "Employer announcements in commute shed",
    category: "growth",
    raw: 7,
    unit: "jobs/1k",
    leadMonthsLow: 12,
    leadMonthsHigh: 24,
    higherIsBetter: true,
    providerKey: "fred",
    core: false,
    whyIgnored: "Needs news and permit records correlated by geography — there is no feed for it.",
    curve: [
      [-OPEN, 0.5, 0, 30],
      [0.5, 2, 30, 55],
      [2, 5, 55, 78],
      [5, 10, 78, 92],
      [10, OPEN, 92, 100],
    ],
    seed: [0.2, 11.4],
  },
  {
    key: "transit_let_dates",
    label: "Transit / road project let dates",
    category: "growth",
    raw: 6,
    unit: "projects",
    leadMonthsLow: 12,
    leadMonthsHigh: 36,
    higherIsBetter: true,
    providerKey: "permits",
    core: false,
    whyIgnored: "Everyone reacts to the announcement; the contract let date is the real trigger.",
    curve: [
      [-OPEN, 0.5, 0, 35],
      [0.5, 1.5, 35, 58],
      [1.5, 3, 58, 78],
      [3, 5, 78, 92],
      [5, OPEN, 92, 100],
    ],
    seed: [0, 5.4],
  },
  {
    key: "school_rezoning",
    label: "School rezoning pressure",
    category: "growth",
    raw: 5,
    unit: "index",
    leadMonthsLow: 3,
    leadMonthsHigh: 9,
    higherIsBetter: true,
    providerKey: "schools",
    core: false,
    whyIgnored: "Boundary changes move prices fast and are buried in school board agendas.",
    curve: [
      [-OPEN, 20, 0, 30],
      [20, 40, 30, 52],
      [40, 60, 52, 72],
      [60, 80, 72, 90],
      [80, OPEN, 90, 100],
    ],
    seed: [18, 88],
  },

  // ── Housing Market Dynamics (25) ─────────────────────────────────────────────
  {
    key: "price_velocity",
    label: "Price velocity",
    category: "housing",
    raw: 10,
    unit: "%/6mo",
    leadMonthsLow: 3,
    leadMonthsHigh: 9,
    higherIsBetter: true,
    providerKey: "mls",
    core: true,
    // Banded, not linear: peaks 5-15% then falls away as bubble risk.
    whyIgnored: "",
    curve: [
      [-OPEN, 0, 0, 25],
      [0, 5, 25, 70],
      [5, 15, 85, 100],
      [15, 25, 70, 45],
      [25, OPEN, 45, 20],
    ],
    seed: [2.4, 9.2],
  },
  {
    key: "inventory_months",
    label: "Months of inventory",
    category: "housing",
    raw: 5,
    unit: "mo",
    leadMonthsLow: 2,
    leadMonthsHigh: 6,
    higherIsBetter: false,
    providerKey: "mls",
    core: true,
    whyIgnored: "",
    curve: [
      [-OPEN, 1.5, 100, 92],
      [1.5, 3, 92, 74],
      [3, 4.5, 74, 52],
      [4.5, 6, 52, 30],
      [6, OPEN, 30, 5],
    ],
    seed: [4.2, 1.5],
  },
  {
    key: "rent_growth",
    label: "Rent growth",
    category: "housing",
    raw: 5,
    unit: "%/yr",
    leadMonthsLow: 3,
    leadMonthsHigh: 9,
    higherIsBetter: true,
    providerKey: "rentcast",
    core: true,
    whyIgnored: "",
    curve: [
      [-OPEN, 0, 0, 25],
      [0, 2, 25, 48],
      [2, 5, 48, 74],
      [5, 9, 74, 92],
      [9, OPEN, 92, 100],
    ],
    seed: [0.8, 8.4],
  },
  {
    key: "price_to_income",
    label: "Price-to-income ratio",
    category: "housing",
    raw: 5,
    unit: "x",
    leadMonthsLow: 12,
    leadMonthsHigh: 24,
    higherIsBetter: false,
    providerKey: "census",
    core: true,
    whyIgnored: "",
    curve: [
      [-OPEN, 3, 100, 90],
      [3, 4, 90, 74],
      [4, 5, 74, 55],
      [5, 6.5, 55, 32],
      [6.5, OPEN, 32, 8],
    ],
    seed: [6.1, 3.4],
  },
  {
    key: "dom_acceleration",
    label: "Days-on-market acceleration",
    category: "housing",
    raw: 9,
    unit: "Δ²days",
    leadMonthsLow: 1,
    leadMonthsHigh: 3,
    higherIsBetter: false,
    providerKey: "mls",
    core: false,
    whyIgnored: "Everyone quotes median DOM. Almost nobody differentiates it twice to catch the turn.",
    curve: [
      [-OPEN, -6, 100, 88],
      [-6, -2, 88, 70],
      [-2, 2, 70, 50],
      [2, 6, 50, 28],
      [6, OPEN, 28, 5],
    ],
    seed: [7.2, -7.4],
  },
  {
    key: "price_cut_frequency",
    label: "Price-cut frequency & depth",
    category: "housing",
    raw: 8,
    unit: "% listings",
    leadMonthsLow: 1,
    leadMonthsHigh: 2,
    higherIsBetter: false,
    providerKey: "mls",
    core: false,
    whyIgnored: "Requires diffing listing history over time — it is not a headline statistic.",
    curve: [
      [-OPEN, 8, 100, 86],
      [8, 16, 86, 68],
      [16, 26, 68, 46],
      [26, 38, 46, 24],
      [38, OPEN, 24, 4],
    ],
    seed: [39, 7.5],
  },
  {
    key: "pending_active_ratio",
    label: "Pending-to-active ratio",
    category: "housing",
    raw: 8,
    unit: "ratio",
    leadMonthsLow: 1,
    leadMonthsHigh: 2,
    higherIsBetter: true,
    providerKey: "mls",
    core: false,
    whyIgnored: "Turns about 45 days before any closed-price index registers the move.",
    curve: [
      [-OPEN, 0.3, 0, 28],
      [0.3, 0.6, 28, 52],
      [0.6, 0.9, 52, 74],
      [0.9, 1.4, 74, 92],
      [1.4, OPEN, 92, 100],
    ],
    seed: [0.24, 1.52],
  },
  {
    key: "withdrawal_relist_rate",
    label: "Withdrawal / relist rate",
    category: "housing",
    raw: 6,
    unit: "% listings",
    leadMonthsLow: 2,
    leadMonthsHigh: 4,
    higherIsBetter: false,
    providerKey: "mls",
    core: false,
    whyIgnored: "The purest seller-conviction tell in the data, and it is published nowhere.",
    curve: [
      [-OPEN, 4, 100, 86],
      [4, 9, 86, 66],
      [9, 15, 66, 44],
      [15, 22, 44, 22],
      [22, OPEN, 22, 4],
    ],
    seed: [21, 3.8],
  },
  {
    key: "cash_purchase_share",
    label: "Cash-purchase share",
    category: "housing",
    raw: 6,
    unit: "% sales",
    leadMonthsLow: 3,
    leadMonthsHigh: 6,
    higherIsBetter: true,
    providerKey: "attom",
    core: false,
    whyIgnored: "The institutional footprint, buried in county deed records.",
    curve: [
      [-OPEN, 12, 0, 32],
      [12, 22, 32, 55],
      [22, 32, 55, 76],
      [32, 45, 76, 92],
      [45, OPEN, 92, 100],
    ],
    seed: [11, 46],
  },
  {
    key: "absentee_buyer_share",
    label: "Absentee / out-of-state buyer share",
    category: "housing",
    raw: 5,
    unit: "% sales",
    leadMonthsLow: 3,
    leadMonthsHigh: 9,
    higherIsBetter: true,
    providerKey: "attom",
    core: false,
    whyIgnored: "Needs the mailing address compared against the situs address, deed by deed.",
    curve: [
      [-OPEN, 8, 0, 32],
      [8, 16, 32, 54],
      [16, 26, 54, 76],
      [26, 38, 76, 92],
      [38, OPEN, 92, 100],
    ],
    seed: [7, 39],
  },

  // ── Infrastructure Development (20) ──────────────────────────────────────────
  {
    key: "building_permits",
    label: "Building permits",
    category: "infrastructure",
    raw: 10,
    unit: "per 10k",
    leadMonthsLow: 9,
    leadMonthsHigh: 18,
    higherIsBetter: true,
    providerKey: "permits",
    core: true,
    whyIgnored: "",
    curve: [
      [-OPEN, 20, 0, 30],
      [20, 50, 30, 54],
      [50, 90, 54, 76],
      [90, 140, 76, 92],
      [140, OPEN, 92, 100],
    ],
    seed: [18, 168],
  },
  {
    key: "new_construction_rate",
    label: "New construction rate",
    category: "infrastructure",
    raw: 5,
    unit: "% stock",
    leadMonthsLow: 12,
    leadMonthsHigh: 24,
    higherIsBetter: true,
    providerKey: "permits",
    core: true,
    whyIgnored: "",
    curve: [
      [-OPEN, 0.3, 0, 32],
      [0.3, 0.8, 32, 55],
      [0.8, 1.6, 55, 78],
      [1.6, 3, 78, 94],
      [3, OPEN, 94, 100],
    ],
    seed: [0.2, 3.2],
  },
  {
    key: "public_investment",
    label: "Public investment",
    category: "infrastructure",
    raw: 5,
    unit: "$/capita",
    leadMonthsLow: 12,
    leadMonthsHigh: 30,
    higherIsBetter: true,
    providerKey: "permits",
    core: true,
    whyIgnored: "",
    curve: [
      [-OPEN, 100, 0, 30],
      [100, 300, 30, 54],
      [300, 700, 54, 78],
      [700, 1400, 78, 94],
      [1400, OPEN, 94, 100],
    ],
    seed: [90, 1620],
  },
  {
    key: "permit_mix_shift",
    label: "Permit mix shift (reno/ADU vs new-build)",
    category: "infrastructure",
    raw: 8,
    unit: "ratio",
    leadMonthsLow: 9,
    leadMonthsHigh: 18,
    higherIsBetter: true,
    providerKey: "permits",
    core: false,
    whyIgnored: "A gentrification precursor that needs every permit classified by type first.",
    curve: [
      [-OPEN, 0.4, 0, 30],
      [0.4, 0.8, 30, 54],
      [0.8, 1.3, 54, 76],
      [1.3, 2.2, 76, 92],
      [2.2, OPEN, 92, 100],
    ],
    seed: [0.32, 2.4],
  },
  {
    key: "commercial_adjacency",
    label: "Commercial permits within 1 mile",
    category: "infrastructure",
    raw: 7,
    unit: "permits",
    leadMonthsLow: 12,
    leadMonthsHigh: 24,
    higherIsBetter: true,
    providerKey: "permits",
    core: false,
    whyIgnored: "Amenity arrival. Nobody spatially joins commercial permits to residential parcels.",
    curve: [
      [-OPEN, 2, 0, 30],
      [2, 6, 30, 54],
      [6, 14, 54, 78],
      [14, 26, 78, 93],
      [26, OPEN, 93, 100],
    ],
    seed: [1, 29],
  },
  {
    key: "permit_cycle_time",
    label: "Permit-to-completion cycle time",
    category: "infrastructure",
    raw: 5,
    unit: "days",
    leadMonthsLow: 6,
    leadMonthsHigh: 12,
    higherIsBetter: false,
    providerKey: "permits",
    core: false,
    whyIgnored: "Municipal friction — it tells you when supply actually lands, not when it was approved.",
    curve: [
      [-OPEN, 120, 100, 88],
      [120, 200, 88, 70],
      [200, 300, 70, 48],
      [300, 420, 48, 26],
      [420, OPEN, 26, 6],
    ],
    seed: [430, 118],
  },
  {
    key: "utility_hookups",
    label: "New utility hookups / water meters",
    category: "infrastructure",
    raw: 7,
    unit: "per 10k",
    leadMonthsLow: 6,
    leadMonthsHigh: 12,
    higherIsBetter: true,
    providerKey: "permits",
    core: false,
    whyIgnored: "Ground truth for occupancy growth — it beats the Census by about a year.",
    curve: [
      [-OPEN, 15, 0, 30],
      [15, 40, 30, 55],
      [40, 80, 55, 78],
      [80, 130, 78, 93],
      [130, OPEN, 93, 100],
    ],
    seed: [13, 141],
  },

  // ── Quality of Life (15) — includes Florida carry-cost risk ──────────────────
  {
    key: "crime_safety",
    label: "Crime safety",
    category: "quality",
    raw: 8,
    unit: "index",
    leadMonthsLow: 6,
    leadMonthsHigh: 18,
    higherIsBetter: true,
    providerKey: "crime",
    core: true,
    whyIgnored: "",
    curve: [
      [-OPEN, 30, 0, 28],
      [30, 50, 28, 50],
      [50, 70, 50, 72],
      [70, 85, 72, 90],
      [85, OPEN, 90, 100],
    ],
    seed: [34, 92],
  },
  {
    key: "school_quality",
    label: "School quality",
    category: "quality",
    raw: 4,
    unit: "/10",
    leadMonthsLow: 12,
    leadMonthsHigh: 36,
    higherIsBetter: true,
    providerKey: "schools",
    core: true,
    whyIgnored: "",
    curve: [
      [-OPEN, 3, 0, 25],
      [3, 5, 25, 48],
      [5, 7, 48, 70],
      [7, 8.5, 70, 90],
      [8.5, OPEN, 90, 100],
    ],
    seed: [3.2, 9.1],
  },
  {
    key: "walkability",
    label: "Walkability",
    category: "quality",
    raw: 3,
    unit: "score",
    leadMonthsLow: 24,
    leadMonthsHigh: 60,
    higherIsBetter: true,
    providerKey: "mapbox",
    core: true,
    whyIgnored: "",
    curve: [
      [-OPEN, 20, 0, 25],
      [20, 40, 25, 48],
      [40, 60, 48, 70],
      [60, 80, 70, 90],
      [80, OPEN, 90, 100],
    ],
    seed: [18, 82],
  },
  {
    key: "insurance_trajectory",
    label: "Insurance premium trajectory",
    category: "quality",
    raw: 9,
    unit: "%/yr",
    leadMonthsLow: 3,
    leadMonthsHigh: 12,
    higherIsBetter: false,
    providerKey: "attom",
    core: false,
    whyIgnored: "The number one killer of Florida cash flow, and almost nobody models its slope.",
    curve: [
      [-OPEN, 4, 100, 88],
      [4, 9, 88, 70],
      [9, 16, 70, 48],
      [16, 26, 48, 24],
      [26, OPEN, 24, 4],
    ],
    seed: [27, 3.6],
  },
  {
    key: "roof_age_distribution",
    label: "Roof-age distribution (15yr+ share)",
    category: "quality",
    raw: 6,
    unit: "% stock",
    leadMonthsLow: 6,
    leadMonthsHigh: 18,
    higherIsBetter: false,
    providerKey: "attom",
    core: false,
    whyIgnored: "Florida insurers refuse 15-year-plus roofs, which forces sales nobody saw coming.",
    curve: [
      [-OPEN, 12, 100, 88],
      [12, 24, 88, 70],
      [24, 38, 70, 48],
      [38, 55, 48, 24],
      [55, OPEN, 24, 5],
    ],
    seed: [56, 11],
  },
  {
    key: "assessed_market_gap",
    label: "Assessed-to-market gap",
    category: "quality",
    raw: 5,
    unit: "%",
    leadMonthsLow: 9,
    leadMonthsHigh: 15,
    higherIsBetter: false,
    providerKey: "attom",
    core: false,
    whyIgnored: "Predicts the property-tax shock that lands the year after you buy.",
    curve: [
      [-OPEN, 8, 100, 88],
      [8, 18, 88, 68],
      [18, 30, 68, 46],
      [30, 45, 46, 22],
      [45, OPEN, 22, 4],
    ],
    seed: [46, 7.4],
  },
  {
    key: "hoa_cdd_escalation",
    label: "HOA / CDD fee escalation",
    category: "quality",
    raw: 5,
    unit: "%/yr",
    leadMonthsLow: 6,
    leadMonthsHigh: 12,
    higherIsBetter: false,
    providerKey: "attom",
    core: false,
    whyIgnored: "Central Florida CDD debt is brutal and is almost never priced into a pro forma.",
    curve: [
      [-OPEN, 3, 100, 88],
      [3, 7, 88, 70],
      [7, 13, 70, 48],
      [13, 20, 48, 24],
      [20, OPEN, 24, 5],
    ],
    seed: [21, 2.6],
  },
  {
    key: "flood_zone_risk",
    label: "Flood / wind zone reclassification risk",
    category: "quality",
    raw: 6,
    unit: "index",
    leadMonthsLow: 6,
    leadMonthsHigh: 24,
    higherIsBetter: false,
    providerKey: "attom",
    core: false,
    whyIgnored: "FEMA map amendments reprice a whole street overnight, with years of warning in the docket.",
    curve: [
      [-OPEN, 15, 100, 88],
      [15, 32, 88, 68],
      [32, 52, 68, 46],
      [52, 72, 46, 22],
      [72, OPEN, 22, 4],
    ],
    seed: [76, 12],
  },

  // ── Economic Fundamentals (5) — includes yield & distress ────────────────────
  {
    key: "employment_rate",
    label: "Employment rate",
    category: "economic",
    raw: 3,
    unit: "%",
    leadMonthsLow: 6,
    leadMonthsHigh: 12,
    higherIsBetter: true,
    providerKey: "fred",
    core: true,
    whyIgnored: "",
    curve: [
      [-OPEN, 91, 0, 30],
      [91, 94, 30, 55],
      [94, 96, 55, 76],
      [96, 97.5, 76, 92],
      [97.5, OPEN, 92, 100],
    ],
    seed: [92.8, 97.6],
  },
  {
    key: "business_growth",
    label: "Business formation growth",
    category: "economic",
    raw: 2,
    unit: "%/yr",
    leadMonthsLow: 9,
    leadMonthsHigh: 18,
    higherIsBetter: true,
    providerKey: "fred",
    core: true,
    whyIgnored: "",
    curve: [
      [-OPEN, 0, 0, 28],
      [0, 2, 28, 52],
      [2, 5, 52, 76],
      [5, 9, 76, 92],
      [9, OPEN, 92, 100],
    ],
    seed: [-0.6, 9.4],
  },
  {
    key: "rent_to_price_spread",
    label: "Rent-to-price spread vs metro",
    category: "economic",
    raw: 6,
    unit: "bps",
    leadMonthsLow: 3,
    leadMonthsHigh: 9,
    higherIsBetter: true,
    providerKey: "rentcast",
    core: false,
    whyIgnored: "Yield compression means capital is already flowing in — before any price index says so.",
    curve: [
      [-OPEN, -60, 0, 30],
      [-60, -20, 30, 52],
      [-20, 20, 52, 72],
      [20, 70, 72, 90],
      [70, OPEN, 90, 100],
    ],
    seed: [-74, 86],
  },
  {
    key: "rental_concessions",
    label: "Rental concession prevalence",
    category: "economic",
    raw: 4,
    unit: "% listings",
    leadMonthsLow: 1,
    leadMonthsHigh: 3,
    higherIsBetter: false,
    providerKey: "rentcast",
    core: false,
    whyIgnored: "Free-month offers soften months before any published rent index moves.",
    curve: [
      [-OPEN, 4, 100, 86],
      [4, 10, 86, 66],
      [10, 18, 66, 44],
      [18, 28, 44, 22],
      [28, OPEN, 22, 4],
    ],
    seed: [29, 3.4],
  },
  {
    key: "str_adr_occupancy",
    label: "STR ADR × occupancy trend",
    category: "economic",
    raw: 4,
    unit: "index",
    leadMonthsLow: 3,
    leadMonthsHigh: 12,
    higherIsBetter: true,
    providerKey: "rentcast",
    core: false,
    whyIgnored: "Orlando-critical, and one city ordinance can reset it overnight.",
    curve: [
      [-OPEN, 30, 0, 30],
      [30, 50, 30, 52],
      [50, 68, 52, 74],
      [68, 84, 74, 92],
      [84, OPEN, 92, 100],
    ],
    seed: [28, 88],
  },
  {
    key: "preforeclosure_trend",
    label: "Pre-foreclosure filing trend",
    category: "economic",
    raw: 5,
    unit: "%/yr",
    leadMonthsLow: 6,
    leadMonthsHigh: 12,
    higherIsBetter: false,
    providerKey: "attom",
    core: false,
    whyIgnored: "The distress-supply pipeline, visible in the clerk's docket months ahead.",
    curve: [
      [-OPEN, -10, 100, 88],
      [-10, 0, 88, 70],
      [0, 12, 70, 48],
      [12, 28, 48, 24],
      [28, OPEN, 24, 4],
    ],
    seed: [31, -14],
  },
  {
    key: "vacancy_proxy",
    label: "Vacancy proxy (mail-return + idle utility)",
    category: "economic",
    raw: 4,
    unit: "%",
    leadMonthsLow: 3,
    leadMonthsHigh: 6,
    higherIsBetter: false,
    providerKey: "census",
    core: false,
    whyIgnored: "Real vacancy rather than the survey estimate, and two datasets have to be joined to see it.",
    curve: [
      [-OPEN, 4, 100, 88],
      [4, 8, 88, 68],
      [8, 13, 68, 46],
      [13, 20, 46, 22],
      [20, OPEN, 22, 4],
    ],
    seed: [22, 3.6],
  },
];

/** Signals with their raw weights renormalised so each category sums to its published weight. */
export function weightedDefs(): (SignalDef & { weight: number })[] {
  return SIGNALS.map((s, i) => {
    const cat = CATEGORIES.find((c) => c.key === s.category);
    const catWeight = cat ? cat.weight : 0;
    const rawSum = SIGNALS.filter((o) => o.category === s.category).reduce((a, o) => a + o.raw, 0);
    return { ...s, weight: (s.raw / rawSum) * catWeight, sortOrder: i };
  });
}

export const SIGNAL_BY_KEY = new Map(SIGNALS.map((s) => [s.key, s]));
